import json
import sys

with open("settings.json", 'r') as file:
    settings = json.load(file)

SUBSAMPLING_FACTOR = settings["CONFIG"]["SUBSAMPLING_FACTOR"]
TRAIN_VALIDATION_SPLIT = settings["CONFIG"]["TRAIN_VALIDATION_SPLIT"]
KFOLD_SPLITS = settings["CONFIG"]["KFOLD_SPLITS"]
DATASET_CHUNKS = settings["CONFIG"]["DATASET_CHUNKS"]
PHASE_PICK_ENSURED_CROP_RATIO = settings["CONFIG"]["PHASE_PICK_ENSURED_CROP_RATIO"]
PHASE_ENSURING_MARGIN = settings["CONFIG"]["PHASE_ENSURING_MARGIN"]
TEST_RATIO = settings["CONFIG"]["SINGLE_SPLIT_TEST_RATIO"]
APPLY_RESAMPLING = settings["CONFIG"]["APPLY_RESAMPLING"]
RESAMPLE_EQ_RATIO = settings["CONFIG"]["RESAMPLE_EQ_RATIO"]

WINDOW_SIZE = 30.

INSTANCE_TIME_WINDOW = 120.0
STEAD_TIME_WINDOW = 60.0

FREQMIN = 1.0
FREQMAX = 20.0

N_CHANNELS = 3

BATCH_SIZE = 256

SAMPLING_FREQ = 100
